version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_MQTT_URL=ws://localhost:9001
    depends_on:
      - server
      - mqtt

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - rover-maps:/tmp/rover_maps
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - POSTGRES_HOST=db
      - POSTGRES_DB=roverdb
      - POSTGRES_USER=roveruser
      - POSTGRES_PASSWORD=roverpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - mqtt
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mqtt:
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSockets
    volumes:
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=roverdb
      - POSTGRES_USER=roveruser
      - POSTGRES_PASSWORD=roverpass
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  mqtt-data:
  mqtt-log:
  postgres-data:
  redis-data:
  pgadmin-data:
  rover-maps:
