# Generated by Django 5.1 on 2025-05-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rover_rovertelemetry_sensorreading_substation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rovertelemetry',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.RemoveField(
            model_name='substation',
            name='location',
        ),
        migrations.AddField(
            model_name='substation',
            name='latitude',
            field=models.FloatField(default=-23.55052),
        ),
        migrations.AddField(
            model_name='substation',
            name='longitude',
            field=models.FloatField(default=-46.633308),
        ),
        migrations.AlterField(
            model_name='rovertelemetry',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rovertelemetry',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
