# Generated by Django 5.1 on 2025-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rovertelemetry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
