# Generated by Django 5.1 on 2025-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_substation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='voltage',
            field=models.CharField(default='500kV', max_length=20),
        ),
    ]
