# Generated by Django 5.1 on 2025-05-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_substation_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='alerts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rover',
            name='battery_level',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='rover',
            name='sensors',
            field=models.JSONField(default=dict),
        ),
    ]
